accounts/urls.py
from django.urls import path
from .views import *
from rest_framework.routers import DefaultRouter


router = DefaultRouter()

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('success/', SuccessView.as_view(), name='success'),

    # APIs for Client
    path('api/v1/add-client/', ADDClientViewSet.as_view({'post': 'create'}), name='add-client-api'),
    path('api/v1/update-client/<int:pk>/', ADDClientViewSet.as_view({'patch': 'partial_update'}), name='update-client-api'),
    path('api/v1/authenticate-api/<int:client_id>/', AuthenticateClientAPI.as_view(), name='authenticate_client_api'),

    ] + router.urls

dashboard/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path(r'', DashboardView.as_view(), name='home'),
    # Profile views
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileUpdateView.as_view(), name='profile-update'),

    # Api Credentials Page
    path('profile/<int:pk>/api/details/', APIDetailsView.as_view(), name='api-details'),

    # Order Book
    path('trade_book', TradeBook.as_view(), name='trade-book'),

    # Realtime Signals
    path('signals/', RealtimeSignals.as_view(), name='realtime-signals'),

    # Webhook for signals
    path('signal_webook/', signal_webhook, name='signal-webhook')
]

neuralwave/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include(('accounts.urls', 'accounts'), namespace='accounts')),
    path(r"", include(('dashboard.urls', 'dashboard'),namespace='dashboard')),
    path(r"", include(('landingpage.urls', 'landingpage'),namespace='landingpage')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models


class TradeSignals(models.Model):
    script_name = models.CharField(max_length=255, null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    strike_price = models.BigIntegerField(null=True, blank=True)
    type = models.CharField(max_length=5, null=True, blank=True, choices=(('Buy', 'BUY'),
                                                                          ('Sell', 'SELL')))

dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from neuralwave.validators import validate_phone_number


class ProfileForm(forms.Form):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'phone_number')

dashboard/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .forms import *
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from accounts.models import CustomUser
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.models import Broker, Client
from .helpers import AliceBlue, Angelone
from rest_framework.views import APIView
from django.http import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt
from dashboard.models import TradeSignals
from pya3 import *
import pya3 as ab


class DashboardView(TemplateView):
    template_name = 'dashboard/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cv'] = dict()

        user = self.request.user
        client = Client.objects.get(user=user)
        if client.broker.broker_symbol == 'ALCB':
            alice = AliceBlue(user)
            alice.get_profile(context['cv'])
            alice.get_position_book(context['cv'])
        if client.broker.broker_symbol == 'ANGL':
            angel = Angelone(user)
            angel.get_profile(context['cv'])
            angel.get_position_book(context['cv'])
            angel.get_capital(context['cv'])
        return context


class TradeBook(TemplateView):
    template_name = 'dashboard/trade_book.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cv'] = dict()
        user = self.request.user
        client = Client.objects.get(user=user)
        if client.broker.broker_symbol == 'ALCB':
            alice = AliceBlue(user)

        if client.broker.broker_symbol == 'ANGL':
            angel = Angelone(user)
            angel.get_trade_book(context['cv'])

        return context



class ProfileDetailView(DetailView):
    template_name = 'dashboard/profile_settings/profile-page.html'
    model = CustomUser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = CustomUser.objects.filter(id=self.request.user.id).first()
        return context


class ProfileUpdateView(UpdateView):
    model = CustomUser
    success_url = reverse_lazy('dashboard:home')
    fields = ('first_name', 'last_name', 'email', 'phone_number')
    template_name = 'dashboard/profile_settings/profile-page.html'

    def form_invalid(self, form):
        # Form data is invalid, handle the invalid form data
        # Example: Display error messages to the user
        print(form.errors)
        return super().form_invalid(form)

    def get_object(self, queryset=None):
        # Return the object to be updated
        print("User ",CustomUser.objects.get(pk=self.kwargs['pk']) )
        return CustomUser.objects.get(pk=self.kwargs['pk'])


class UserAPIView(TemplateView):
    template_name = 'dashboard/user-api.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = CustomUser.objects.filter(id=self.request.user.id).first()
        return context


class APIDetailsView(TemplateView):
    template_name = 'dashboard/profile_settings/user-api.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['api_details'] = dict()

        brokers_list = Broker.objects.all()
        api_details = Client.objects.filter(user=self.request.user)
        if api_details.exists():
            context['api_details']['details'] = api_details.first()
            context['api_details']['is_have'] = True
        else:
            context['api_details']['is_have'] = False

        context['brokers_list'] = brokers_list
        return context


def signal_webhook(request):
    if request.method == 'POST':
        try:
            print("Here", request)
            # json_str = str(request.body.decode('utf-8'))
            # print("String", json_str)
            # payload = json.loads(json_str)
            # print("JSON ", payload)
            # script_name = payload['script_name']
            # price = payload['price']
            # type = payload['type']
            # print("Working here ")
            # trade_signal = TradeSignals.objects.create(script_name=script_name, price=price, type=type)
            # trade_signal.save()
            print("hereeree")
            user = request.user
            print(user)
            client = Client.objects.get(user=user)
            print(client.broker.broker_symbol)
            if client.broker.broker_symbol == 'ALCB':
                print("here")
                # alice = AliceBlue(user)
                # alice.place_options_order('NIFTY')
                alice_b = ab.Aliceblue(user_id=client.client_user_id, api_key=client.client_id)
                alice_b.get_session_id()
                alice_b.place_order(
                    transaction_type=ab.TransactionType.Buy,
                    instrument=alice_b.get_instrument_by_symbol('NSE', 'NIFTY'),
                    quantity=25,
                    order_type=OrderType.Market,
                    product_type=ProductType.Intraday,
                    price=0.0,
                    trigger_price=None,
                    stop_loss=None,
                    square_off=None,
                    trailing_sl=None,
                    is_amo=False,
                    order_tag='order1',
                )

            return JsonResponse({'status': 'success'})
        except json.JSONDecodeError:
            return JsonResponse({'status': 'error', 'message': 'Invalid JSON'}, status=400)
        return JsonResponse({'status': 'error', 'message': 'Only POST requests are allowed'}, status=405)


class RealtimeSignals(TemplateView):
    template_name = 'dashboard/signals.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

templates/dashboard/profile_settings/profile-page.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default" data-assets-path="../assets/"
  data-template="vertical-menu-template-free">

<head>
  <meta charset="utf-8" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
  <title>Dashboard - Account | Aladdin</title>

  <meta name="description" content="" />

  <!-- Favicon -->
  {% include 'common/common_css.html' %}
  {% block common_css %}
  {% endblock %}
</head>

<body>
  <!-- Layout wrapper -->
  <div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">
      <!-- Menu -->

      {% include 'dashboard/sidebar.html' %}
      {% block sidebar %}
      {% endblock %}
      <!-- / Menu -->

      <!-- Layout container -->
      <div class="layout-page">
        {% include 'dashboard/topnavbar.html' %}
        {% block topnavbar %}
        {% endblock%}

        <!-- Content wrapper -->
        <div class="content-wrapper">
          <!-- Content -->

          <div class="container-xxl flex-grow-1 container-p-y">
            <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Account Settings</span> </h4>

            <div class="row">
              <div class="col-md-12">
                <ul class="nav nav-pills flex-column flex-md-row mb-3">
                  <li class="nav-item">
                    <a class="nav-link active" href="javascript:void(0);"><i class="bx bx-user me-1"></i> Account</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:api-details' request.user.id %}"><i class="bx bx-link-alt me-1"></i> API</a>
                  </li>
                </ul>
                <div class="card mb-4">
                  <h5 class="card-header">Profile Details</h5>
                  <!-- Account -->
                  <hr class="my-0">
                  <div class="card-body">
                    <form id="formAccountSettings" method="POST" action="{% url 'dashboard:profile-update' request.user.id %}">
                      {% csrf_token %}
                      <div class="row">
                        <div class="mb-3 col-md-6">
                          <label for="firstName" class="form-label">First Name</label>
                          <input class="form-control" type="text" id="firstName" name="first_name" value="{% if user.first_name is none %}{% else %}{{user.first_name}}{% endif %}" autofocus="">
                        </div>
                        <div class="mb-3 col-md-6">
                          <label for="lastName" class="form-label">Last Name</label>
                          <input class="form-control" type="text" name="last_name" id="last_name" value="{% if user.last_name is none %}{% else %}{{user.last_name}}{% endif %}">
                        </div>
                        <div class="mb-3 col-md-6">
                          <label for="email" class="form-label">E-mail</label>
                          <input class="form-control" type="text" id="email" name="email" value="{% if user.email is none %}{% else %}{{user.email}}{% endif %}" placeholder="john.doe@example.com">
                        </div>
                        
                        <div class="mb-3 col-md-6">
                          <label class="form-label" for="phoneNumber">Phone Number</label>
                          <div class="input-group input-group-merge">
                            <span class="input-group-text">India (+91)</span>
                            <input type="text" id="phoneNumber" name="phone_number" class="form-control" placeholder="202 555 0111" value="{% if user.phone_number is none %}{% else %}{{user.phone_number}}{% endif %}">
                          </div>
                        </div>

      
                        
                        
                      </div>
                      <div class="mt-2">
                        <button type="submit" class="btn btn-primary me-2">Save changes</button>
                        <!-- <button type="reset" class="btn btn-outline-secondary">Clear</button> -->
                      </div>
                    </form>
                  </div>
                  <!-- /Account -->
                </div>
                <div class="card">
                  <h5 class="card-header">Delete Account</h5>
                  <div class="card-body">
                    <div class="mb-3 col-12 mb-0">
                      <div class="alert alert-warning">
                        <h6 class="alert-heading fw-bold mb-1">Are you sure you want to delete your account?</h6>
                        <p class="mb-0">Once you delete your account, there is no going back. Please be certain.</p>
                      </div>
                    </div>
                    <form id="formAccountDeactivation" onsubmit="return false">
                      <div class="form-check mb-3">
                        <input class="form-check-input" type="checkbox" name="accountActivation" id="accountActivation">
                        <label class="form-check-label" for="accountActivation">I confirm my account deactivation</label>
                      </div>
                      <button type="submit" class="btn btn-danger deactivate-account">Deactivate Account</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- / Content -->

          {% include 'dashboard/footer.html' %}
          {% block footer %}
          {% endblock %}

          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
  </div>
  <!-- / Layout wrapper -->


  <!-- Core JS -->
  {% include 'common/common_js.html' %}
  {% block common_js %}
  {% endblock%}
  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>

</html>

templates/dashboard/profile_settings/user-api.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default" data-assets-path="../assets/"
  data-template="vertical-menu-template-free">

<head>
  <meta charset="utf-8" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
  <title>Dashboard - API | Aladdin</title>

  <meta name="description" content="" />

  <!-- Favicon -->
  {% include 'common/common_css.html' %}
  {% block common_css %}
  {% endblock %}
</head>

<body>
  <!-- Layout wrapper -->
  <div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">
      <!-- Menu -->

      {% include 'dashboard/sidebar.html' %}
      {% block sidebar %}
      {% endblock %}
      <!-- / Menu -->

      <!-- Layout container -->
      <div class="layout-page">
        {% include 'dashboard/topnavbar.html' %}
        {% block topnavbar %}
        {% endblock%}

        <!-- Content wrapper -->
        <div class="content-wrapper">
          <!-- Content -->

          <div class="container-xxl flex-grow-1 container-p-y">
            <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Account Settings</span></h4>

            <div class="row">
              <div class="col-md-12">
                <ul class="nav nav-pills flex-column flex-md-row mb-3">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:profile' request.user.id %}"><i
                        class="bx bx-user me-1"></i> Account</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="{% url 'dashboard:profile' request.user.id %}"><i
                        class="bx bx-link-alt me-1"></i> API</a>
                  </li>
                </ul>
                <div class="card mb-4">
                  <h5 class="card-header">API Details</h5>
                  <!-- Account -->
                  <hr class="my-0">
                  <div class="card-body">
                    <form id="client-api-form" method="POST"
                      action="{% url 'dashboard:profile-update' request.user.id %}">
                      {% csrf_token %}
                      <div class="row">
                        <div class="mb-3 col-md-6">
                          <label for="firstName" class="form-label">USER ID</label>
                          <input class="form-control" type="text" id="firstName" name="client_user_id"
                            value="{% if api_details.is_have %}{{api_details.details.client_user_id}}{% endif %}"
                            autofocus="" placeholder="User ID" {% if api_details.is_have %} disabled {% endif %}>
                        </div>
                        <div class="mb-3 col-md-6">
                          <label for="firstName" class="form-label">Password</label>
                          <input class="form-control" type="text" id="firstName" name="client_password"
                            value="{% if api_details.is_have %}{{api_details.details.client_password}}{% endif %}"
                            autofocus="" placeholder="User ID" {% if api_details.is_have %} disabled {% endif %}>
                        </div>
                        <div class="mb-3 col-md-6">
                          <label for="firstName" class="form-label">API KEY</label>
                          <input class="form-control" type="text" id="firstName" name="client_id"
                            value="{% if api_details.is_have %}{{api_details.details.client_id}}{% endif %}"
                            autofocus="" placeholder="API Key" {% if api_details.is_have %} disabled {% endif %}>
                        </div>
                        <div class="mb-3 col-md-6">
                          <label for="lastName" class="form-label">API Secrect</label>
                          <input class="form-control" type="text" name="client_secret" id="last_name"
                            value="{% if api_details.is_have %}{{api_details.details.client_secret}}{% endif %}"
                            placeholder="API Secret" {% if api_details.is_have %} disabled {% endif %}>
                        </div>
                        <div class="mb-3 col-md-6">
                          <label for="email" class="form-label">TOTP KEY</label>
                          <input class="form-control" type="text" id="email" name="totp"
                            value="{% if api_details.is_have %}{{api_details.details.totp}}{% endif %}"
                            placeholder="2 Factor Authentication Key" {% if api_details.is_have %} disabled {% endif %}>
                        </div>

                        <div class="mb-3 col-md-6">
                          <label for="defaultSelect" class="form-label">Choose Broker</label>
                          <select id="defaultSelect" class="form-select" name="broker" {% if api_details.is_have %} disabled {% endif %}>
                            <option>Default select</option>
                            {% for broker in brokers_list %}
                              <option value="{{broker.id}}" {% if api_details.is_have %} {% if broker.id == api_details.details.broker_id %} selected {% endif %} {% endif %}>{{broker.name}}</option>
                            {% endfor %}
                          </select>
                        </div>
                        
                        
                        <div class="mb-3 col-md-6">
                          <label for="defaultSelect" class="form-label">TOTP</label>
                          <input class="form-control" type="text" id="email" name="otp" placeholder="TOTP">
                        </div>

                      </div>

                      <div class="mb-3 col-md-6">
                        {% if not api_details.is_have %}
                        <div class="alert alert-danger" role="alert">API Details are not found! Please enter it!</div>
                        {% endif %}

                        {% if api_details.is_have %}
                          {% if not api_details.details.connected %}
                          <div class="alert alert-danger" role="alert">API is not connected! Click button below to connect</div>
                          {% elif api_details.details.connected %}
                          <div class="alert alert-success" role="alert">API is connected successfully! </div>
                          {% endif %}

                        {% endif %}

                        
                      </div>

                      <div class="mt-2">
                        <button type="submit" class="btn btn-primary me-2 {% if api_details.is_have %} updateable {% endif %}">Save changes</button>
                        <button id="edit-api-form" type="button" class="btn btn-secondary me-2">Edit Form</button>
                        <button type="button" class="connect_api btn me-2 {% if api_details.details.connected %} btn-outline-success {% else %} btn-outline-primary {% endif%}" {% if api_details.details.connected %} disabled {% endif%}> {% if api_details.details.connected %} Connected {% else %} Connect {% endif %}</button>
                        {% if api_details.details.connected %}<button type="button" class="connect_api btn btn-outline-primary me-2">Re-Connect</button> {% endif %}
                        <!-- <button type="reset" class="btn btn-outline-secondary">Clear</button> -->
                      </div>
                    </form>
                  </div>
                  <!-- /Account -->
                </div>

              </div>
            </div>
          </div>
          <!-- / Content -->

          {% include 'dashboard/footer.html' %}
          {% block footer %}
          {% endblock %}

          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
  </div>
  <!-- / Layout wrapper -->


  <!-- Core JS -->
  {% include 'common/common_js.html' %}
  {% block common_js %}
  {% endblock%}
  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <script>
    // Assuming you have included jQuery library

    function getChangedFields(initialData) {
      var changedData = {};
      $('#client-api-form').find('input, select, textarea').each(function() {
        var name = this.name;
        var currentValue = $(this).val();
        if (initialData[name] !== currentValue) {
          changedData[name] = currentValue;
        }
      });
      return changedData;
    }

    var initialFormData = {};
    $(document).ready(function () {
      // Assuming you have a form with id "client-form" and input fields for client details
      $("#edit-api-form").on("click", function(){
        $('#client-api-form').find('input, select, textarea').each(function() {
          $(this).removeAttr('disabled')
        });
      })

      $('#client-api-form').find('input, select, textarea').each(function() {
        initialFormData[this.name] = $(this).val();
      });
      
      $('#client-api-form').submit(function (event) {
        // Prevent the default form submission
        event.preventDefault();

        var changedFields = getChangedFields(initialFormData);
        if ($.isEmptyObject(changedFields)) {
            alert("No changes detected.");
            return;
        }

        // Serialize the form data
        var formData = $(this).serialize();
        console.log(this, event, formData)
        if($(event.originalEvent.submitter).hasClass('updateable')){
          
          // Send PUT request to update the client
          $.ajax({
            type: 'PATCH',
            url: '/accounts/api/v1/update-client/{{api_details.details.id}}/',
            data: changedFields,
            headers: {
            'X-CSRFToken': getCookie('csrftoken')
            },
            success: function(response) {
              console.log('Client updated successfully:', response);
              window.location.reload();
            },
            error: function(xhr, status, error) {
              console.error('Failed to update client:', error);
            }
          });

        }
        else{
          // AJAX request to create a new client
          $.ajax({
            url: '/accounts/api/v1/add-client/',  // URL for creating clients
            type: 'POST',
            data: formData,
            headers: {
            'X-CSRFToken': getCookie('csrftoken')
            },
            success: function (response) {
              // Client created successfully, handle the response
              console.log('Client created:', response);
              window.location.reload();
              // You can perform further actions like showing a success message or redirecting the user
            },
            error: function (xhr, status, error) {
              // Error occurred while creating client, handle the error
              console.error('Error creating client:', error);
              // You can display an error message to the user or handle the error in any other way
            }
          });

        }

      });
    });

    // Authenticate API form
    $(document).ready(function () {
      $('.connect_api').on('click', function (event) {
        event.preventDefault(); // Prevent form submission

        // Send POST request to the authentication API
        var totp = $("input[name='otp']").val()
        console.log(totp)
        $.ajax({
          type: 'POST',
          url: '/accounts/api/v1/authenticate-api/'+"{{api_details.details.id}}"+"/",
          headers: {
            'X-CSRFToken': getCookie('csrftoken')
          },
          data:{
            "totp": totp
          },
          dataType: 'json',
          success: function (response) {
            // Authentication successful
            console.log('Authentication successful:', response);
            if(response.connected){
              window.location.reload();
            }
            // Redirect to a new page or perform other actions
          },
          error: function (xhr, status, error) {
            // Authentication failed
            console.error('Authentication failed:', error);
            // Display an error message or take other actions
          }
        });
        

      });
    });

  </script>
</body>

</html>