accounts/urls.py
from django.urls import path
from .views import *
from rest_framework.routers import DefaultRouter


router = DefaultRouter()

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('success/', SuccessView.as_view(), name='success'),

    # APIs for Client
    path('api/v1/add-client/', ADDClientViewSet.as_view({'post': 'create'}), name='add-client-api'),
    path('api/v1/update-client/<int:pk>/', ADDClientViewSet.as_view({'patch': 'partial_update'}), name='update-client-api'),
    path('api/v1/authenticate-api/<int:client_id>/', AuthenticateClientAPI.as_view(), name='authenticate_client_api'),

    ] + router.urls

landingpage/urls.py
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path(r'home/', LandingPageHome.as_view(), name='landing_page_home'),
    path(r'about/', LandingPageAbout.as_view(), name='landing_page_about'),
    path(r'services/', LandingPageServices.as_view(), name='landing_page_services'),
    path(r'contact/', LandingPageContact.as_view(), name='landing_page_contact')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

neuralwave/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include(('accounts.urls', 'accounts'), namespace='accounts')),
    path(r"", include(('dashboard.urls', 'dashboard'),namespace='dashboard')),
    path(r"", include(('landingpage.urls', 'landingpage'),namespace='landingpage')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landingpage/models.py
from django.db import models

# Create your models here.

landingpage/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class LandingPageHome(TemplateView):
    template_name = 'landingpage/home.html'


class LandingPageAbout(TemplateView):
    template_name = 'landingpage/about.html'


class LandingPageServices(TemplateView):
    template_name = 'landingpage/services.html'


class LandingPageContact(TemplateView):
    template_name = 'landingpage/contact.html'

templates/landingpage/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>About</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    {% include 'landingpage/common_css.html' %}
    {% block l_common_css.html %}
    {% endblock %}
</head>

<body>
    {% include 'landingpage/topbar.html' %}
    {% block l_topbar %}
    {% endblock %}

    <!-- Page Header Start -->
    <div class="container-fluid page-header py-5">
        <div class="container text-center py-5">
            <h1 class="display-2 text-white mb-4 animated slideInDown">About Us</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a href="{% url 'landingpage:landing_page_home' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'landingpage:landing_page_home' %}">Pages</a></li>
                    <li class="breadcrumb-item" aria-current="page">About</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Fact Start -->
    <div class="container-fluid bg-secondary py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 wow fadeIn" data-wow-delay=".1s">
                    <div class="d-flex counter">
                        <h1 class="me-3 text-primary counter-value">99</h1>
                        <h5 class="text-white mt-1">Success in getting happy customer</h5>
                    </div>
                </div>
                <div class="col-lg-3 wow fadeIn" data-wow-delay=".3s">
                    <div class="d-flex counter">
                        <h1 class="me-3 text-primary counter-value">25</h1>
                        <h5 class="text-white mt-1">Thousands of successful business</h5>
                    </div>
                </div>
                <div class="col-lg-3 wow fadeIn" data-wow-delay=".5s">
                    <div class="d-flex counter">
                        <h1 class="me-3 text-primary counter-value">120</h1>
                        <h5 class="text-white mt-1">Total clients who love HighTech</h5>
                    </div>
                </div>
                <div class="col-lg-3 wow fadeIn" data-wow-delay=".7s">
                    <div class="d-flex counter">
                        <h1 class="me-3 text-primary counter-value">5</h1>
                        <h5 class="text-white mt-1">Stars reviews given by satisfied clients</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Fact End -->


    <!-- About Start -->
    <div class="container-fluid py-5 my-5">
        <div class="container pt-5">
            <div class="row g-5">
                <div class="col-lg-5 col-md-6 col-sm-12 wow fadeIn" data-wow-delay=".3s">
                    <div class="h-100 position-relative">
                        <img src="{% static 'landingpage/new_img/img1.jpeg' %}" class="img-fluid w-75 rounded" alt="" style="margin-bottom: 25%;">
                        <div class="position-absolute w-75" style="top: 25%; left: 25%;">
                            <img src="{% static 'landingpage/new_img/img2.jpeg' %}" class="img-fluid w-100 rounded" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-7 col-md-6 col-sm-12 wow fadeIn" data-wow-delay=".5s">
                    <h5 class="text-primary">About Us</h5>
                    <h1 class="mb-4">About Neural Wave Signal And It's Innovative Algo Solutions</h1>
                    <p>At Neural Wave Signal, we are pioneers in revolutionizing the landscape of algorithmic trading.
                        With a dedication to innovation and excellence, we harness the power of neural networks to
                        decode market signals and deliver actionable insights. Our mission is to empower investors with
                        cutting-edge technology, enabling them to navigate the complexities of the financial markets
                        with confidence. </p>
                    <p class="mb-4">Backed by a team of experts and driven by a passion for performance, we strive to
                        redefine the future of trading, one wave at a time. Join us in our journey towards financial
                        mastery and let Neural Wave Signal be your guide to success in the dynamic world of trading.</p>
                    <a href="" class="btn btn-secondary rounded-pill px-5 py-3 text-white">More Details</a>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->


    {% include 'landingpage/footer.html' %}
    {% block l_footer %}
    {% endblock %}


    
    {% include 'landingpage/common_js.html' %}
    {% block l_common_js %}
    {% endblock %}
</body>

</html>

templates/landingpage/common_css.html
{% load static %}

{% block l_common_css %}
<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
    href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Saira:wght@500;600;700&display=swap"
    rel="stylesheet">

<!-- Icon Font Stylesheet -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
<link href="{% static 'landingpage/lib/animate/animate.min.css' %}" rel="stylesheet">
<link href="{% static 'landingpage/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static 'landingpage/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Template Stylesheet -->
<link href="{% static 'landingpage/css/style.css' %}" rel="stylesheet">
{% endblock %}

templates/landingpage/common_js.html
{% load static %}

{% block l_common_js %}
<!-- JavaScript Libraries -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="{% static 'landingpage/lib/wow/wow.min.js' %}"></script>
<script src="{% static 'landingpage/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'landingpage/lib/waypoints/waypoints.min.js' %}"></script>
<script src="{% static 'landingpage/lib/owlcarousel/owl.carousel.min.js' %}"></script>

<!-- Template Javascript -->
<script src="{% static 'landingpage/js/main.js' %}"></script>
<script>
    function getCookie(name) {
        const value = `; ${document.cookie}`;
        const parts = value.split(`; ${name}=`);
        if (parts.length === 2) return parts.pop().split(';').shift();
    }

    function setCookie(name, value, days) {
        var expires = "";
        if (days) {
            var date = new Date();
            date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
            expires = "; expires=" + date.toUTCString();
        }

        var existingCookie = getCookie(name);
        if (existingCookie !== null) {
            document.cookie = name + "=" + value + expires + "; path=/";
        } else {
            document.cookie = name + "=" + value + expires + "; path=/";
        }
    }

</script>
{% endblock %}

templates/landingpage/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Contact</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    {% include 'landingpage/common_css.html' %}
    {% block l_common_css.html %}
    {% endblock %}
</head>

<body>
    {% include 'landingpage/topbar.html' %}
    {% block l_topbar %}
    {% endblock %}

    <!-- Page Header Start -->
     <div class="container-fluid page-header py-5">
        <div class="container text-center py-5">
            <h1 class="display-2 text-white mb-4 animated slideInDown">Contact Us</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a href="{% url 'landingpage:landing_page_home' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'landingpage:landing_page_home' %}">Pages</a></li>
                    <li class="breadcrumb-item" aria-current="page">Contact</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->

    <!-- Fact Start -->
    <div class="container-fluid bg-secondary py-5">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 wow fadeIn" data-wow-delay=".1s">
                    <div class="d-flex counter">
                        <h1 class="me-3 text-primary counter-value">99</h1>
                        <h5 class="text-white mt-1">Success in getting happy customer</h5>
                    </div>
                </div>
                <div class="col-lg-3 wow fadeIn" data-wow-delay=".3s">
                    <div class="d-flex counter">
                        <h1 class="me-3 text-primary counter-value">25</h1>
                        <h5 class="text-white mt-1">Thousands of successful business</h5>
                    </div>
                </div>
                <div class="col-lg-3 wow fadeIn" data-wow-delay=".5s">
                    <div class="d-flex counter">
                        <h1 class="me-3 text-primary counter-value">120</h1>
                        <h5 class="text-white mt-1">Total clients who love HighTech</h5>
                    </div>
                </div>
                <div class="col-lg-3 wow fadeIn" data-wow-delay=".7s">
                    <div class="d-flex counter">
                        <h1 class="me-3 text-primary counter-value">5</h1>
                        <h5 class="text-white mt-1">Stars reviews given by satisfied clients</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Fact End -->

    <!-- Contact Start -->
    <div class="container-fluid py-5 mb-5">
        <div class="container">
            <!-- <div class="text-center mx-auto pb-5 wow fadeIn" data-wow-delay=".3s" style="max-width: 600px;">
                    <h5 class="text-primary">Get In Touch</h5>
                    <h1 class="mb-3">Contact for any query</h1>
                    <p class="mb-2">The contact form is currently inactive. Get a functional and working contact form with Ajax & PHP in a few minutes. Just copy and paste the files, add a little code and you're done. <a href="https://htmlcodex.com/contact-form">Download Now</a>.</p>
                </div> -->
            <div class="contact-detail position-relative p-5">
                <div class="row g-5 mb-5 justify-content-center">
                    <div class="col-xl-4 col-lg-6 wow fadeIn" data-wow-delay=".3s">
                        <div class="d-flex bg-light p-3 rounded">
                            <div class="flex-shrink-0 btn-square bg-secondary rounded-circle"
                                style="width: 64px; height: 64px;">
                                <i class="fas fa-map-marker-alt text-white"></i>
                            </div>
                            <div class="ms-3">
                                <h4 class="text-primary">Address</h4>
                                <a href="https://goo.gl/maps/Zd4BCynmTb98ivUJ6" target="_blank" class="h5">New Delhi,
                                    India</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-6 wow fadeIn" data-wow-delay=".5s">
                        <div class="d-flex bg-light p-3 rounded">
                            <div class="flex-shrink-0 btn-square bg-secondary rounded-circle"
                                style="width: 64px; height: 64px;">
                                <i class="fa fa-phone text-white"></i>
                            </div>
                            <div class="ms-3">
                                <h4 class="text-primary">Call Us</h4>
                                <a class="h5" href="tel:+0123456789" target="_blank">+91 8745033653</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-6 wow fadeIn" data-wow-delay=".7s">
                        <div class="d-flex bg-light p-3 rounded">
                            <div class="flex-shrink-0 btn-square bg-secondary rounded-circle"
                                style="width: 64px; height: 64px;">
                                <i class="fa fa-envelope text-white"></i>
                            </div>
                            <div class="ms-3">
                                <h4 class="text-primary">Email Us</h4>
                                <a class="h5" href="mailto:info@example.com"
                                    target="_blank">neuralwavesignal@gmail.com</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row g-5">
                    <div class="col-lg-6 wow fadeIn" data-wow-delay=".3s">
                        <div class="p-5 h-100 rounded contact-map">
                            <iframe class="rounded w-100 h-100"
                                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3025.4710403339755!2d-73.82241512404069!3d40.685622471397615!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c26749046ee14f%3A0xea672968476d962c!2s123rd%20St%2C%20Queens%2C%20NY%2C%20USA!5e0!3m2!1sen!2sbd!4v1686493221834!5m2!1sen!2sbd"
                                style="border:0;" allowfullscreen="" loading="lazy"
                                referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                    </div>
                    <div class="col-lg-6 wow fadeIn" data-wow-delay=".5s">
                        <div class="p-5 rounded contact-form">
                            <form action="mailto:neuralwavesignal@gmail.com" method="get" enctype="text/plain">
                                <div class="mb-4">
                                    <input type="text" class="form-control border-0 py-3" placeholder="Your Name">
                                </div>
                                <div class="mb-4">
                                    <input type="email" class="form-control border-0 py-3" placeholder="Your Email">
                                </div>
                                <div class="mb-4">
                                    <textarea class="w-100 form-control border-0 py-3" rows="6" cols="10"
                                        placeholder="Message"></textarea>
                                </div>
                                <div class="text-start">
                                    <button class="btn bg-primary text-white py-3 px-5" type="submit">Send
                                        Message</button>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


    {% include 'landingpage/footer.html' %}
    {% block l_footer %}
    {% endblock %}


    

    {% include 'landingpage/common_js.html' %}
    {% block l_common_js %}
    {% endblock %}
</body>

</html>

templates/landingpage/footer.html
{% load static %}

{% block l_footer %}
<!-- Footer Start -->
<div class="container-fluid footer bg-dark wow fadeIn" data-wow-delay=".3s">
    <div class="container pt-5 pb-4">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <a href="index.html">
                    <h1 class="text-white fw-bold d-block">Neural <span class="text-secondary">Wave</span> </h1>
                </a>
                <p class="mt-4 text-light">Empowering Investors with Advanced Algorithmic Trading Solutions. Join us
                    in navigating the financial markets with confidence and precision.</p>
                <div class="d-flex hightech-link">
                    <a href="" class="btn-light nav-fill btn btn-square rounded-circle me-2"><i
                            class="fab fa-facebook-f text-primary"></i></a>
                    <a href="" class="btn-light nav-fill btn btn-square rounded-circle me-2"><i
                            class="fab fa-twitter text-primary"></i></a>
                    <a href="" class="btn-light nav-fill btn btn-square rounded-circle me-2"><i
                            class="fab fa-instagram text-primary"></i></a>
                    <a href="" class="btn-light nav-fill btn btn-square rounded-circle me-0"><i
                            class="fab fa-linkedin-in text-primary"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <a href="#" class="h3 text-secondary">Short Link</a>
                <div class="mt-4 d-flex flex-column short-link">
                    <a href="{% url 'landingpage:landing_page_about' %}" class="mb-2 text-white"><i
                            class="fas fa-angle-right text-secondary me-2"></i>About us</a>
                    <a href="{% url 'landingpage:landing_page_contact' %}" class="mb-2 text-white"><i
                            class="fas fa-angle-right text-secondary me-2"></i>Contact us</a>
                    <a href="{% url 'landingpage:landing_page_services' %}" class="mb-2 text-white"><i
                            class="fas fa-angle-right text-secondary me-2"></i>Our Services</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <a href="#" class="h3 text-secondary">Help Link</a>
                <div class="mt-4 d-flex flex-column help-link">
                    <!-- <a href="" class="mb-2 text-white"><i class="fas fa-angle-right text-secondary me-2"></i>Terms Of use</a> -->
                    <a href="./privacy_policy.html" class="mb-2 text-white"><i
                            class="fas fa-angle-right text-secondary me-2"></i>Privacy Policy</a>
                    <a href="./contact.html" class="mb-2 text-white"><i
                            class="fas fa-angle-right text-secondary me-2"></i>Contact</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <a href="#" class="h3 text-secondary">Contact Us</a>
                <div class="text-white mt-4 d-flex flex-column contact-link">
                    <a href="#" class="pb-3 text-light border-bottom border-primary"><i
                            class="fas fa-map-marker-alt text-secondary me-2"></i> New Delhi, India</a>
                    <a href="#" class="py-3 text-light border-bottom border-primary"><i
                            class="fas fa-phone-alt text-secondary me-2"></i> +91 8745033653</a>
                    <a href="#" class="py-3 text-light border-bottom border-primary"><i
                            class="fas fa-envelope text-secondary me-2"></i> neuralwavesignal@gmail.com</a>
                </div>
            </div>
        </div>
        <hr class="text-light mt-5 mb-4">
        <div class="row">
            <div class="col-md-6 text-center text-md-start">
                <span class="text-light"><a href="#" class="text-secondary"><i
                            class="fas fa-copyright text-secondary me-2"></i>Neural Wave</a>, All right
                    reserved.</span>
            </div>
            
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-secondary btn-square rounded-circle back-to-top"><i
    class="fa fa-arrow-up text-white"></i></a>

{% endblock %}

templates/landingpage/topbar.html
{% load static %}

{% block l_topbar %}
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
    <div class="tradingview-widget-container__widget"></div>
    <script type="text/javascript" src="https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js"
        async>
            {
                "symbols": [
                    {
                        "proName": "FOREXCOM:SPXUSD",
                        "title": "S&P 500 Index"
                    },
                    {
                        "proName": "FX_IDC:EURUSD",
                        "title": "EUR to USD"
                    },
                    {
                        "description": "NIFTY50",
                        "proName": "NSE:NIFTY"
                    },
                    {
                        "description": "BANKNIFTY",
                        "proName": "NSE:BANKNIFTY"
                    },
                    {
                        "description": "SENSEX",
                        "proName": "BSE:SENSEX"
                    },
                    {
                        "description": "CRUDEMCX",
                        "proName": "MCX:CRUDEOIL1!"
                    }
                ],
                    "showSymbolLogo": true,
                        "isTransparent": false,
                            "displayMode": "adaptive",
                                "colorTheme": "dark",
                                    "locale": "en"
            }
        </script>
</div>
<!-- TradingView Widget END -->

<!-- Spinner Start -->
<!-- <div id="spinner"
    class="show position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-grow text-primary" role="status"></div>
</div> -->
<!-- Spinner End -->

<!-- Topbar Start -->
<div class="container-fluid bg-dark py-2 d-none d-md-flex">
    <div class="container">
        <div class="d-flex justify-content-between topbar">
            <div class="top-info">
                <small class="me-3 text-white-50"><a href="#"><i
                            class="fas fa-map-marker-alt me-2 text-secondary"></i></a>New Delhi, India</small>
                <small class="me-3 text-white-50"><a href="#"><i
                            class="fas fa-envelope me-2 text-secondary"></i></a>neuralwavesignal@gmail.com</small>
            </div>
            <div id="note" class="text-secondary d-none d-xl-flex"><small>Disclaimer-We are not a SEBI registered
                    Investment Advisor nor we provide any kind of tips or recommendations for investments </small>
            </div>
            <div class="top-link">
                <a target="_blank" href="https://www.facebook.com/profile.php?id=61555940997704"
                    class="bg-light nav-fill btn btn-sm-square rounded-circle"><i
                        class="fab fa-facebook-f text-primary"></i></a>
                <!-- <a href="" class="bg-light nav-fill btn btn-sm-square rounded-circle"><i class="fab fa-twitter text-primary"></i></a> -->
                <a target="_blank" href="https://www.instagram.com/neuralwavesignal/"
                    class="bg-light nav-fill btn btn-sm-square rounded-circle"><i
                        class="fab fa-instagram text-primary"></i></a>
                <!-- <a href="" class="bg-light nav-fill btn btn-sm-square rounded-circle me-0"><i class="fab fa-linkedin-in text-primary"></i></a> -->
            </div>
        </div>
    </div>
</div>
<!-- Topbar End -->

<!-- Navbar Start -->
<div class="container-fluid bg-primary">
    <div class="container">
        <nav class="navbar navbar-dark navbar-expand-lg py-0">
            <a href="index.html" class="navbar-brand">
                <h1 class="text-white fw-bold d-block">Neural <span class="text-secondary"> Wave</span> </h1>
            </a>
            <button type="button" class="navbar-toggler me-0" data-bs-toggle="collapse"
                data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse bg-transparent" id="navbarCollapse">
                <div class="navbar-nav ms-auto mx-xl-auto p-0">
                    <a href="{% url 'landingpage:landing_page_home' %}" class="nav-item nav-link active text-secondary">Home</a>
                    <a href="{% url 'landingpage:landing_page_about' %}" class="nav-item nav-link">About</a>
                    <a href="{% url 'landingpage:landing_page_services' %}" class="nav-item nav-link">Services</a>
                    <!-- <a href="project.html" class="nav-item nav-link">Projects</a> -->
                    <!-- <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu rounded">
                                <a href="blog.html" class="dropdown-item">Our Blog</a>
                                <a href="team.html" class="dropdown-item">Our Team</a>
                                <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                                <a href="404.html" class="dropdown-item">404 Page</a>
                            </div>
                        </div> -->
                    <a href="{% url 'landingpage:landing_page_contact' %}" class="nav-item nav-link">Contact</a>
                </div>
            </div>
            <div class="d-none d-xl-flex flex-shirink-0">
                <div id="phone-tada" class="d-flex align-items-center justify-content-center me-4">
                    <a href="" class="position-relative animated tada infinite">
                        <i class="fa fa-phone-alt text-white fa-2x"></i>
                        <div class="position-absolute" style="top: -7px; left: 20px;">
                            <span><i class="fa fa-comment-dots text-secondary"></i></span>
                        </div>
                    </a>
                </div>
                <div class="d-flex flex-column pe-4 border-end">
                    <span class="text-white-50">Have any questions?</span>
                    <span class="text-secondary">Call: + 91 8745033653</span>
                </div>
                <div class="d-flex align-items-center justify-content-center ms-4 ">
                    <a href="#"><i class="bi bi-search text-white fa-2x"></i> </a>
                </div>
            </div>
        </nav>
    </div>
</div>
<!-- Navbar End -->
{% endblock %}