accounts/urls.py
from django.urls import path
from .views import *
from rest_framework.routers import DefaultRouter


router = DefaultRouter()

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('success/', SuccessView.as_view(), name='success'),

    # APIs for Client
    path('api/v1/add-client/', ADDClientViewSet.as_view({'post': 'create'}), name='add-client-api'),
    path('api/v1/update-client/<int:pk>/', ADDClientViewSet.as_view({'patch': 'partial_update'}), name='update-client-api'),
    path('api/v1/authenticate-api/<int:client_id>/', AuthenticateClientAPI.as_view(), name='authenticate_client_api'),

    ] + router.urls

dashboard/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path(r'', DashboardView.as_view(), name='home'),
    # Profile views
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileUpdateView.as_view(), name='profile-update'),

    # Api Credentials Page
    path('profile/<int:pk>/api/details/', APIDetailsView.as_view(), name='api-details'),

    # Order Book
    path('trade_book', TradeBook.as_view(), name='trade-book'),

    # Realtime Signals
    path('signals/', RealtimeSignals.as_view(), name='realtime-signals'),

    # Webhook for signals
    path('signal_webook/', signal_webhook, name='signal-webhook')
]

neuralwave/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include(('accounts.urls', 'accounts'), namespace='accounts')),
    path(r"", include(('dashboard.urls', 'dashboard'),namespace='dashboard')),
    path(r"", include(('landingpage.urls', 'landingpage'),namespace='landingpage')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models


class TradeSignals(models.Model):
    script_name = models.CharField(max_length=255, null=True, blank=True)
    price = models.FloatField(null=True, blank=True)
    strike_price = models.BigIntegerField(null=True, blank=True)
    type = models.CharField(max_length=5, null=True, blank=True, choices=(('Buy', 'BUY'),
                                                                          ('Sell', 'SELL')))

dashboard/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from neuralwave.validators import validate_phone_number


class ProfileForm(forms.Form):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email', 'phone_number')

dashboard/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .forms import *
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from accounts.models import CustomUser
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.models import Broker, Client
from .helpers import AliceBlue, Angelone
from rest_framework.views import APIView
from django.http import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt
from dashboard.models import TradeSignals
from pya3 import *
import pya3 as ab


class DashboardView(TemplateView):
    template_name = 'dashboard/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cv'] = dict()

        user = self.request.user
        client = Client.objects.get(user=user)
        if client.broker.broker_symbol == 'ALCB':
            alice = AliceBlue(user)
            alice.get_profile(context['cv'])
            alice.get_position_book(context['cv'])
        if client.broker.broker_symbol == 'ANGL':
            angel = Angelone(user)
            angel.get_profile(context['cv'])
            angel.get_position_book(context['cv'])
            angel.get_capital(context['cv'])
        return context


class TradeBook(TemplateView):
    template_name = 'dashboard/trade_book.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cv'] = dict()
        user = self.request.user
        client = Client.objects.get(user=user)
        if client.broker.broker_symbol == 'ALCB':
            alice = AliceBlue(user)

        if client.broker.broker_symbol == 'ANGL':
            angel = Angelone(user)
            angel.get_trade_book(context['cv'])

        return context



class ProfileDetailView(DetailView):
    template_name = 'dashboard/profile_settings/profile-page.html'
    model = CustomUser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = CustomUser.objects.filter(id=self.request.user.id).first()
        return context


class ProfileUpdateView(UpdateView):
    model = CustomUser
    success_url = reverse_lazy('dashboard:home')
    fields = ('first_name', 'last_name', 'email', 'phone_number')
    template_name = 'dashboard/profile_settings/profile-page.html'

    def form_invalid(self, form):
        # Form data is invalid, handle the invalid form data
        # Example: Display error messages to the user
        print(form.errors)
        return super().form_invalid(form)

    def get_object(self, queryset=None):
        # Return the object to be updated
        print("User ",CustomUser.objects.get(pk=self.kwargs['pk']) )
        return CustomUser.objects.get(pk=self.kwargs['pk'])


class UserAPIView(TemplateView):
    template_name = 'dashboard/user-api.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = CustomUser.objects.filter(id=self.request.user.id).first()
        return context


class APIDetailsView(TemplateView):
    template_name = 'dashboard/profile_settings/user-api.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['api_details'] = dict()

        brokers_list = Broker.objects.all()
        api_details = Client.objects.filter(user=self.request.user)
        if api_details.exists():
            context['api_details']['details'] = api_details.first()
            context['api_details']['is_have'] = True
        else:
            context['api_details']['is_have'] = False

        context['brokers_list'] = brokers_list
        return context


def signal_webhook(request):
    if request.method == 'POST':
        try:
            print("Here", request)
            # json_str = str(request.body.decode('utf-8'))
            # print("String", json_str)
            # payload = json.loads(json_str)
            # print("JSON ", payload)
            # script_name = payload['script_name']
            # price = payload['price']
            # type = payload['type']
            # print("Working here ")
            # trade_signal = TradeSignals.objects.create(script_name=script_name, price=price, type=type)
            # trade_signal.save()
            print("hereeree")
            user = request.user
            print(user)
            client = Client.objects.get(user=user)
            print(client.broker.broker_symbol)
            if client.broker.broker_symbol == 'ALCB':
                print("here")
                # alice = AliceBlue(user)
                # alice.place_options_order('NIFTY')
                alice_b = ab.Aliceblue(user_id=client.client_user_id, api_key=client.client_id)
                alice_b.get_session_id()
                alice_b.place_order(
                    transaction_type=ab.TransactionType.Buy,
                    instrument=alice_b.get_instrument_by_symbol('NSE', 'NIFTY'),
                    quantity=25,
                    order_type=OrderType.Market,
                    product_type=ProductType.Intraday,
                    price=0.0,
                    trigger_price=None,
                    stop_loss=None,
                    square_off=None,
                    trailing_sl=None,
                    is_amo=False,
                    order_tag='order1',
                )

            return JsonResponse({'status': 'success'})
        except json.JSONDecodeError:
            return JsonResponse({'status': 'error', 'message': 'Invalid JSON'}, status=400)
        return JsonResponse({'status': 'error', 'message': 'Only POST requests are allowed'}, status=405)


class RealtimeSignals(TemplateView):
    template_name = 'dashboard/signals.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

templates/dashboard/footer.html
{% load static %}

{% block footer %}
<!-- Footer -->
<footer class="content-footer footer bg-footer-theme">
    <div class="container-xxl d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
      <div class="mb-2 mb-md-0">
        ©
        <script>
          document.write(new Date().getFullYear());
        </script>
        , made with ❤️ by
        <a href="https://themeselection.com" target="_blank" class="footer-link fw-bolder">Neural Wave</a>
      </div>
      <div>
        <a href="https://themeselection.com/license/" class="footer-link me-4" target="_blank">License</a>

        <a href="https://github.com/themeselection/sneat-html-admin-template-free/issues" target="_blank"
          class="footer-link me-4">Support</a>
      </div>
    </div>
  </footer>
  <!-- / Footer -->
{% endblock %}

templates/dashboard/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default" data-assets-path="../assets/"
  data-template="vertical-menu-template-free">

<head>
  <meta charset="utf-8" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
  <title>Dashboard - Analytics | Aladdin</title>

  <meta name="description" content="" />

  <!-- Favicon -->
  {% include 'common/common_css.html' %}
  {% block common_css %}
  {% endblock %}
</head>

<body>
  <!-- Layout wrapper -->
  <div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">
      <!-- Menu -->

      {% include 'dashboard/sidebar.html' %}
      {% block sidebar %}
      {% endblock %}
      <!-- / Menu -->

      <!-- Layout container -->
      <div class="layout-page">
        {% include 'dashboard/topnavbar.html' %}
        {% block topnavbar %}
        {% endblock%}

        <!-- Content wrapper -->
        <div class="content-wrapper">
          <!-- Content -->

          <div class="container-xxl flex-grow-1 container-p-y">
            <div class="row">
              <div class="col-lg-8 mb-4 order-0">
                <div class="card">
                  <div class="d-flex align-items-end row">
                    <div class="col-sm-7">
                      <div class="card-body">
                        <h5 class="card-title text-primary">Welcome {{cv.profile.full_name}}! 🎉</h5>
                        <p class="mb-4">
                          Your account has been grown by <span class="fw-bold">{{cv.position_book.today_per_realisedprofitloss}}% </span>today. Check your new trades in your profile.
                        </p>

                        <a href="{% url 'dashboard:trade-book' %}" class="btn btn-sm btn-outline-primary">View Trades</a>
                      </div>
                    </div>
                    <div class="col-sm-5 text-center text-sm-left">
                      <div class="card-body pb-0 px-0 px-md-4">
                        <img src="{% static '/assets/img/illustrations/man-with-laptop-light.png' %}" height="140"
                          alt="View Badge User" data-app-dark-img="illustrations/man-with-laptop-dark.png"
                          data-app-light-img="illustrations/man-with-laptop-light.png" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 col-md-4 order-1">
                <div class="row">
                  <div class="col-lg-6 col-md-12 col-6 mb-4">
                    <div class="card">
                      <div class="card-body">
                        <div class="card-title d-flex align-items-start justify-content-between">
                          <div class="avatar flex-shrink-0">
                            <img src="{% static '/assets/img/icons/unicons/chart-success.png' %}" alt="chart success"
                              class="rounded" />
                          </div>
                          <div class="dropdown">
                            <button class="btn p-0" type="button" id="cardOpt3" data-bs-toggle="dropdown"
                              aria-haspopup="true" aria-expanded="false">
                              <i class="bx bx-dots-vertical-rounded"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="cardOpt3">
                              <a class="dropdown-item" href="javascript:void(0);">View More</a>
                              <a class="dropdown-item" href="javascript:void(0);">Delete</a>
                            </div>
                          </div>
                        </div>
                        <span class="fw-semibold d-block mb-1">Today Profit</span>
                        {% if not cv.position_book.error %}
                          <h3 class="card-title mb-2
                          {% if cv.position_book.today_realisedprofitloss < 0 %}
                          text-danger
                          {% elif cv.position_book.today_realisedprofitloss > 0 %}
                          text-danger
                          {% else %}
                          text-primary
                          {% endif %}
                          
                          ">{{cv.position_book.today_realisedprofitloss}}
                          </h3>
                          <small class=" fw-semibold
                          {% if cv.position_book.today_realisedprofitloss < 0 %}
                          text-danger
                          {% elif cv.position_book.today_realisedprofitloss > 0 %}
                          text-danger
                          {% else %}
                          text-primary
                          {% endif %}
                          
                          "><i class="
                          {% if cv.position_book.today_realisedprofitloss < 0 %}
                          bx bx-down-arrow-alt
                          {% elif cv.position_book.today_realisedprofitloss > 0 %}
                          bx bx-up-arrow-alt
                          {% endif %}
                          "></i> {{cv.position_book.today_per_realisedprofitloss}}%</small>
                        {% else %}
                          <h3 class="card-title mb-2 text-primary fs-5">Data not available</h3>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-6 col-md-12 col-6 mb-4">
                    <div class="card">
                      <div class="card-body">
                        <div class="card-title d-flex align-items-start justify-content-between">
                          <div class="avatar flex-shrink-0">
                            <img src="{% static '/assets/img/icons/unicons/wallet-info.png' %}" alt="Credit Card" class="rounded" />
                          </div>
                          <div class="dropdown">
                            <button class="btn p-0" type="button" id="cardOpt6" data-bs-toggle="dropdown"
                              aria-haspopup="true" aria-expanded="false">
                              <i class="bx bx-dots-vertical-rounded"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="cardOpt6">
                              <a class="dropdown-item" href="javascript:void(0);">View More</a>
                              <a class="dropdown-item" href="javascript:void(0);">Delete</a>
                            </div>
                          </div>
                        </div>
                        <span>Algo Profit</span>
                        {% if not cv.position_book.error %}
                          <h3 class="card-title mb-2
                          {% if cv.position_book.today_realisedprofitloss < 0 %}
                          text-danger
                          {% elif cv.position_book.today_realisedprofitloss > 0 %}
                          text-danger
                          {% else %}
                          text-primary
                          {% endif %}
                          
                          ">{{cv.position_book.today_realisedprofitloss}}
                          </h3>
                          <small class=" fw-semibold
                          {% if cv.position_book.today_realisedprofitloss < 0 %}
                          text-danger
                          {% elif cv.position_book.today_realisedprofitloss > 0 %}
                          text-danger
                          {% else %}
                          text-primary
                          {% endif %}
                          
                          "><i class="
                          {% if cv.position_book.today_realisedprofitloss < 0 %}
                          bx bx-down-arrow-alt
                          {% elif cv.position_book.today_realisedprofitloss > 0 %}
                          bx bx-up-arrow-alt
                          {% endif %}
                          "></i> {{cv.position_book.today_per_realisedprofitloss}}%</small>
                        {% else %}
                          <h3 class="card-title mb-2 text-primary fs-5">Data not available</h3>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
              

            </div>
            <div class="row">
              
            </div>
          </div>
          <!-- / Content -->

          {% include 'dashboard/footer.html' %}
          {% block footer %}
          {% endblock %}

          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
  </div>
  <!-- / Layout wrapper -->


  <!-- Core JS -->
  {% include 'common/common_js.html' %}
  {% block common_js %}
  {% endblock%}
  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>

</html>

templates/dashboard/sidebar.html
{% load static %}

{% block sidebar %}
<!-- Menu -->
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
    <div class="app-brand demo">
        <a href="index.html" class="app-brand-link">
            <span class="app-brand-logo demo">
                <img src="{% static 'assets/img/logos/aladdin.png' %}" alt="" width="50">
            </span>
            <span class="app-brand-text demo menu-text fw-bolder ms-2">Alladin</span>
        </a>

        <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
        </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
        <!-- Dashboard -->
        <li class="menu-item active">
            <a href="{% url 'dashboard:home' %}" class="menu-link">
                <i class="menu-icon tf-icons bx bx-home-circle"></i>
                <div data-i18n="Analytics">Dashboard</div>
            </a>
        </li>

        <!-- Layouts -->
        <li class="menu-item">
            <a href="javascript:void(0);" class="menu-link menu-toggle">
                <i class="menu-icon tf-icons bx bx-layout"></i>
                <div data-i18n="Layouts">Accounts</div>
            </a>

            <ul class="menu-sub">
                <li class="menu-item">
                    <a href="{% url 'dashboard:profile' request.user.id %}" class="menu-link">
                        <div data-i18n="Without menu">Profile</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="{% url 'dashboard:api-details' request.user.id %}" class="menu-link">
                        <div data-i18n="Without navbar">API Details</div>
                    </a>
                </li>
            </ul>
        </li>
        <li class="menu-item">
            <a href="{% url 'dashboard:trade-book' %}" class="menu-link">
                <!-- <i class="menu-icon tf-icons bx bx-home-circle"></i> -->
                <svg class="menu-icon tf-icons" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: ;msFilter:;"><path d="M6 19h1v3h2v-3h1a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1H9V2H7v3H6a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1zM7 7h2v10H7zm7 10h1v3h2v-3h1a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1h-1V4h-2v3h-1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1zm1-8h2v6h-2z"></path></svg>
               
                <div data-i18n="Analytics">Trade Book</div>
            </a>
        </li>

        <li class="menu-item">
            <a href="{% url 'dashboard:realtime-signals' %}" class="menu-link">
               <svg class="menu-icon tf-icons d-flex align-items-center" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);transform: ;msFilter:;"><path d="M3 16h2v5H3zm4-3h2v8H7zm4-3h2v11h-2zm4-3h2v14h-2zm4-3h2v17h-2z"></path></svg>
                <div data-i18n="Analytics">Realtime Signals</div>
            </a>
        </li>


    </ul>
</aside>
<!-- / Menu -->
{% endblock %}

templates/dashboard/signals.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="light-style layout-menu-fixed" dir="ltr" data-theme="theme-default" data-assets-path="../assets/"
  data-template="vertical-menu-template-free">

<head>
  <meta charset="utf-8" />
  <meta name="viewport"
    content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
  <title>Dashboard - Realtime Signals | Aladdin</title>

  <meta name="description" content="" />

  <!-- Favicon -->
  {% include 'common/common_css.html' %}
  {% block common_css %}
  {% endblock %}

  <style>
    .signals_card_buy{
        background-color: #55AD9B !important;
        color: white;
    }
    .signals_card_sell{
        background-color: #FF6969 !important;
        color: white;
    }
  </style>
</head>

<body>
  <!-- Layout wrapper -->
  <div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">
      <!-- Menu -->

      {% include 'dashboard/sidebar.html' %}
      {% block sidebar %}
      {% endblock %}
      <!-- / Menu -->

      <!-- Layout container -->
      <div class="layout-page">
        {% include 'dashboard/topnavbar.html' %}
        {% block topnavbar %}
        {% endblock%}

        <!-- Content wrapper -->
        <div class="content-wrapper">
          <!-- Content -->
          <div class="container-xxl flex-grow-1 container-p-y">
            <div class="card p-5">
            <div class="h5">Today's Realtime Signals</div>
            <div class="row">
                
                <div class="col-md-6 col-xl-3">
                    <div class="border border-1 signals_card_buy">
                        <div class="d-flex flex-column  p-2 w-75">
                            <div><span>SCRIPT: </span> <span> <strong>NIFTY</strong> </span></div>
                            <div><span>PRICE: </span> <span> <strong>23400</strong>  </span></div>
                            <div><span>TYPE: </span> <span> <strong>BUY</strong>  </span></div>
                            <div><span>TIME: </span> <span> <strong>10:05:05</strong>  </span></div>
                        </div>
                        <div>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 col-xl-3">
                    <div class="border border-1 signals_card_sell">
                        <div class="d-flex flex-column  p-2 w-75">
                            <div><span>SCRIPT: </span> <span> <strong>BANKNIFTY</strong> </span></div>
                            <div><span>PRICE: </span> <span> <strong>55400</strong>  </span></div>
                            <div><span>TYPE: </span> <span> <strong>SELL</strong>  </span></div>
                            <div><span>TIME: </span> <span> <strong>10:10:05</strong>  </span></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

          </div>


          
          <!-- / Content -->

          {% include 'dashboard/footer.html' %}
          {% block footer %}
          {% endblock %}

          <div class="content-backdrop fade"></div>
        </div>
        <!-- Content wrapper -->
      </div>
      <!-- / Layout page -->
    </div>

    <!-- Overlay -->
    <div class="layout-overlay layout-menu-toggle"></div>
  </div>
  <!-- / Layout wrapper -->


  <!-- Core JS -->
  {% include 'common/common_js.html' %}
  {% block common_js %}
  {% endblock%}
  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>

</html>

templates/dashboard/topnavbar.html
{% load static %}

{% block topnavbar %}
<!-- Navbar -->
<nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">
  <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
    <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
      <i class="bx bx-menu bx-sm"></i>
    </a>
  </div>

  <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
    <!-- Search -->
    <!-- <div class="navbar-nav align-items-center">
      <div class="nav-item d-flex align-items-center">
        <i class="bx bx-search fs-4 lh-0"></i>
        <input type="text" class="form-control border-0 shadow-none" placeholder="Search..." aria-label="Search...">
      </div>
    </div> -->
    <!-- /Search -->

    <ul class="navbar-nav flex-row align-items-center ms-auto">
      <!-- Place this tag where you want the button to render. -->
      <li class="nav-item lh-1 me-3">
        <span></span>
      </li>

      <!-- User -->
      <li class="nav-item navbar-dropdown dropdown-user dropdown">
        <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
          <div class="avatar avatar-online">
            <img src="{% static '/assets/img/avatars/1.png' %}" alt="" class="w-px-40 h-auto rounded-circle">
          </div>
        </a>
        <ul class="dropdown-menu dropdown-menu-end">
          <li>
            <a class="dropdown-item" href="#">
              <div class="d-flex">
                <div class="flex-shrink-0 me-3">
                  <div class="avatar avatar-online">
                    <img src="{% static '/assets/img/avatars/1.png' %}" alt="" class="w-px-40 h-auto rounded-circle">
                  </div>
                </div>
                <div class="flex-grow-1">
                  <span class="fw-semibold d-block">{{request.user.first_name}} {{request.user.last_name}}</span>
                  <small class="text-muted">{% if request.user.is_staff %} Admin {% else %} Trader {% endif %} </small>
                </div>
              </div>
            </a>
          </li>
          <li>
            <div class="dropdown-divider"></div>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'dashboard:profile' request.user.id %}">
              <i class="bx bx-user me-2"></i>
              <span class="align-middle">My Profile</span>
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="#">
              <i class="bx bx-cog me-2"></i>
              <span class="align-middle">Settings</span>
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="#">
              <span class="d-flex align-items-center align-middle">
                <i class="flex-shrink-0 bx bx-credit-card me-2"></i>
                <span class="flex-grow-1 align-middle">Billing</span>
                <span class="flex-shrink-0 badge badge-center rounded-pill bg-danger w-px-20 h-px-20">4</span>
              </span>
            </a>
          </li>
          <li>
            <div class="dropdown-divider"></div>
          </li>
          <li>
            <a class="dropdown-item" href="auth-login-basic.html">
              <i class="bx bx-power-off me-2"></i>
              <span class="align-middle">Log Out</span>
            </a>
          </li>
        </ul>
      </li>
      <!--/ User -->
    </ul>
  </div>
</nav>

<!-- / Navbar -->

{% endblock %}